name: Node.js CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_to_staging:
    runs-on: ubuntu-latest

    steps:
      # Your existing build and push steps...

  deploy_to_staging:
    needs: build_and_push_to_staging
    runs-on: ubuntu-latest

    steps:
      # Your existing deployment steps for staging...

  deploy_to_production:
    needs: deploy_to_staging
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Manual approval step, waiting for approval..."
          # Implement a manual approval mechanism (e.g., sending a notification or requiring a response).

      - name: Deploy to Production Server
        if: success() && github.event_name != 'workflow_dispatch'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Log in to the Docker Hub
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            # Replace this with your deployment script
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/nodejs:staging
            docker stop nodejs
            docker rm nodejs
            docker run -d -p 80:8080 --name nodejs ${{secrets.DOCKERHUB_USERNAME}}/nodejs:staging
