name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to the Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t kevin/nodejs .
      
      - name: Push update image to Dockerhub
        run: docker push kevin/nodejs

      - name: SSH Deploy to Server
        if: success() # Only deploy if the previous steps were successful
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            #Login to the DockerHub
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            # Replace this with your deployment script
            docker pull kevin/nodejs
            docker stop nodejs
            docker rm nodejs
            docker run -d -p 80:8080 --name nodejs kevin/nodejs
